services:
  beautique-db:
    container_name: beautique-db
    image: postgres:latest
    environment:
      POSTGRES_DB: beautique
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - "./init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql"
    networks:
      - beautique-network
    ports:
      - "3334:5432"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - beautique-network
  mongodb:
    image: "mongo:latest"
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    networks:
      - beautique-network

networks:
  beautique-network:
    driver: bridge
